# Generated by Django 4.2.6 on 2023-10-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectbox_app', '0002_boxproject_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxproject',
            name='img',
        ),
    ]
